[
  ["http://calf.sourceforge.net/plugins/Analyzer", -1, 0, "Calf Analyzer"],
  ["http://calf.sourceforge.net/plugins/BassEnhancer", -1, 0, "Calf Bass Enhancer"],
  ["http://calf.sourceforge.net/plugins/CompensationDelay", -1, 0, "Calf Compensation Delay Line"],
  ["http://calf.sourceforge.net/plugins/Compressor", -1, 0, "Calf Compressor"],
  ["http://calf.sourceforge.net/plugins/Crusher", -1, 0, "Calf Crusher"],
  ["http://calf.sourceforge.net/plugins/Deesser", -1, 0, "Calf Deesser"],
  ["http://calf.sourceforge.net/plugins/Emphasis", -1, 0, "Calf Emphasis"],
  ["http://calf.sourceforge.net/plugins/Equalizer12Band", -1, 0, "Calf Equalizer 12 Band"],
  ["http://calf.sourceforge.net/plugins/Exciter", -1, 0, "Calf Exciter"],
  ["http://calf.sourceforge.net/plugins/Filter", -1, 0, "Calf Filter"],
  ["http://calf.sourceforge.net/plugins/Flanger", -1, 0, "Calf Flanger"],
  ["http://calf.sourceforge.net/plugins/Gate", -1, 0, "Calf Gate"],
  ["http://calf.sourceforge.net/plugins/HaasEnhancer", -1, 0, "Calf Haas Stereo Enhancer"],
  ["http://calf.sourceforge.net/plugins/Limiter", -1, 0, "Calf Limiter"],
  ["http://calf.sourceforge.net/plugins/MonoCompressor", -1, 0, "Calf Mono Compressor"],
  ["http://calf.sourceforge.net/plugins/MultibandCompressor", -1, 0, "Calf Multiband Compressor"],
  ["http://calf.sourceforge.net/plugins/Phaser", -1, 0, "Calf Phaser"],
  ["http://calf.sourceforge.net/plugins/Pulsator", -1, 0, "Calf Pulsator"],
  ["http://calf.sourceforge.net/plugins/Reverb", -1, 0, "Calf Reverb"],
  ["http://calf.sourceforge.net/plugins/ReverseDelay", -1, 0, "Calf Reverse Delay"],
  ["http://calf.sourceforge.net/plugins/RingModulator", -1, 0, "Calf Ring Modulator"],
  ["http://calf.sourceforge.net/plugins/RotarySpeaker", -1, 0, "Calf Rotary Speaker"],
  ["http://calf.sourceforge.net/plugins/Saturator", -1, 0, "Calf Saturator"],
  ["http://calf.sourceforge.net/plugins/StereoTools", -1, 0, "Calf Stereo Tools"],
  ["http://calf.sourceforge.net/plugins/TapeSimulator", -1, 0, "Calf Tape Simulator"],
  ["http://calf.sourceforge.net/plugins/TransientDesigner", -1, 0, "Calf Transient Designer"],
  ["http://calf.sourceforge.net/plugins/VintageDelay", -1, 0, "Calf Vintage Delay"],
  ["/usr/lib64/ladspa/filter.so", 1, 1042, "hpf"],
  ["/usr/lib64/ladspa/filter.so", 0, 1041, "lpf"]
]
